server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: discovery-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://discovery-server:8761/eureka/